<?php

const CODE_SUCCESS = 200;

const CODE_CREATED = 201;

const CODE_REDIRECT = 302;

const CODE_SERVER_ERROR = 500;

const CODE_BLACKLISTED_USER = 419; // TOKEN EXPIRED

const HTTP_PAYMENT_REQUIRED = 402; //INSUFFICIENT FUNDS

const HTTP_FORBIDDEN = 403; //FORBINDIN

const HTTP_NOT_FOUND = 404; //NOT FOUND

const HTTP_METHOD_NOT_ALLOWED = 405;

const HTTP_BAD_REQUEST = 400; //SERVER ERROR

const CODE_VALIDATION_ERROR = 422; //VALIDATION ERROR

const HTTP_UNAUTHORIZED = 401; //TOKEN EXPIRED

const HTTP_NOT_ACCEPTABLE = 406; //UNREGISTERD ACCOUNT

const HTTP_EXPECTATION_FAILED = 417; //NO TOKEN PROVIDED

const HTTP_PRECONDITION_FAILED = 412; //INVALID DETAILS

const HTTP_REQUEST_TIMEOUT = 408;

const HTTP_TOO_MANY_REQUESTS = 429;
